# Generated by Django 3.2.4 on 2021-06-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dht11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moisturelvl', models.IntegerField()),
            ],
        ),
    ]
