# Generated by Django 3.2.4 on 2021-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='moisture',
        ),
        migrations.AddField(
            model_name='dht11',
            name='Moisturelvl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
