# Generated by Django 3.2.4 on 2021-06-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createmodels', '0002_auto_20210619_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Moisturelvl', models.IntegerField()),
                ('DataDate', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='dht11',
        ),
    ]
